server {
    listen 8080;

    location /aktivTabell {
        proxy_pass http://pensjon-regler/aktivTabell;
    }

    location /alleSatstabeller {
        proxy_pass http://pensjon-regler/alleSatstabeller;
    }

    location /api/ {
        proxy_pass http://pensjon-regler/api/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }
}