server {
    listen 8080;
    resolver kube-dns.kube-system.svc.cluster.local valid=30s;

    location /aktivTabell {
        set $upstream http://pensjon-regler.pensjon-regler.svc.cluster.local;
        proxy_pass $upstream$request_uri;
    }

    location /alleSatstabeller {
        set $upstream http://pensjon-regler.pensjon-regler.svc.cluster.local;
        proxy_pass $upstream$request_uri;
    }

    location /api/ {
        set $upstream http://pensjon-regler.pensjon-regler.svc.cluster.local;
        proxy_pass $upstream$request_uri;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }
}