name: 'Merge Main to Sandbox'

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ['Automerge Dependabot']
    branches: [main]
    types:
      - completed

jobs:

  mergeMainToSandbox:
    if: github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Merge Main to Sandbox
        uses: robotology/gh-action-nightly-merge@v1.5.2
        with:
          stable_branch: 'main'
          development_branch: 'sandbox'
          allow_ff: true
          allow_forks: true
          user_name: GitHub Merge Actions
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
