name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: write
      packages: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate tag
        id: tag
        env:
          TZ: Europe/Oslo
        run: |
          timestamp=$(TZ=Europe/Oslo date '+%Y.%m.%d-%H%M')
          sha=$(git rev-parse --short HEAD)
          echo "TAG=${timestamp}-${sha}" >> $GITHUB_OUTPUT
          echo "Debug - Generated tag value:"
          cat $GITHUB_OUTPUT
      - name: Build and push image and SBOM to OCI registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pensjon-regler
          tag: ${{ steps.tag.outputs.TAG }}
      - name: Replace tag in image
        id: replace-tag
        run: |
          original_image="${{ steps.docker-build-push.outputs.image }}"
          new_image="${original_image%:*}:${{ steps.tag.outputs.TAG }}"
          echo "IMAGE=${new_image}" >> $GITHUB_OUTPUT
      - name: Deploy to Nais
        uses: nais/deploy/actions/deploy@v2
        env:
          TZ: Europe/Oslo
          CLUSTER: dev-gcp
          RESOURCE: nais.yml
          VAR: image=${{ steps.replace-tag.outputs.IMAGE }}
          TELEMETRY: ${{ steps.docker-build-push.outputs.telemetry }}