## Varsler Slack-kanal om BAU pull-requests som trenger godkjenning
name: Slack-varsel for BAU pull-requests

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [main]

jobs:
  slack-varsel:
    if: |
      github.event.pull_request.draft == false &&
      startsWith(github.head_ref, 'bau/')
    name: Send Slack-varsel om BAU PR
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v6
      - name: Send melding til Slack
        run: |
          PAYLOAD="payload={ \"text\": \"<!here> :eyes: \nEn BAU pull-request trenger godkjenning!\n*<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>*\nOpprettet av: \${slack_id}\" }"
          "${GITHUB_WORKSPACE}/.github/slack.sh" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          AUTHOR: ${{ github.event.pull_request.user.login }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
